# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTemplate < Formula
  desc "Goreleaser testing description"
  homepage "https://github.com/robinovitch61/goreleaser-testing"
  version "0.8.0"

  on_macos do
    url "https://github.com/robinovitch61/goreleaser-testing/releases/download/0.8.0/ goreleaser-testing_ 0.8.0_Darwin_all"
    sha256 "602aa5c6e9752d46e8e71ae0fe83274badb60afac491ad4c1abdaf2a4a1ad4b0"

    def install
      bin.install "goreleaser-testing"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/0.8.0/ goreleaser-testing_ 0.8.0_Linux_x86_64"
      sha256 "98c78e64032fe9e80a134c27db057a821c4618b7c64ac6cd17ee6ed9c5f50866"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/0.8.0/ goreleaser-testing_ 0.8.0_Linux_arm64"
      sha256 "eff77c8bc496122d7d3c3c17aaf8fb9392b98cc73b32618ef88651a2e029e069"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end
end
