# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc "Goreleaser testing description"
  homepage "https://github.com/robinovitch61/goreleaser-testing"
  version "0.14.0"

  on_macos do
    url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.14.0/goreleaser-testing_0.14.0_Darwin_all.tar.gz"
    sha256 "b4e72ebaff0c9bb1421cd3c8a94aca733fa1acadc06472f1c2f56588a003193c"

    def install
      bin.install "goreleaser-testing"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.14.0/goreleaser-testing_0.14.0_Linux_arm64.tar.gz"
      sha256 "23f0354ca2ce9cd8401a354e2a21e59ffc57dfdc46085df8a3bc04667044c13f"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.14.0/goreleaser-testing_0.14.0_Linux_x86_64.tar.gz"
      sha256 "41c31810f36273ff568165f9cd5361389c194084e13f34003f65c08d87307687"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end
end
