# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserTesting < Formula
  desc "Goreleaser testing description"
  homepage "https://github.com/robinovitch61/goreleaser-testing"
  version "0.33.0"

  on_macos do
    url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.33.0/goreleaser-testing_0.33.0_Darwin_all.tar.gz"
    sha256 "24267abea4e0b773a0c7b4a538ca586c33a3b1be22a40066ac5af861e84a9422"

    def install
      bin.install "goreleaser-testing"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.33.0/goreleaser-testing_0.33.0_Linux_arm64.tar.gz"
      sha256 "38eee4bc8dc8bf33bab3343858835cf0b89a5927aa28a8389ff1b54dc97fa6e2"

      def install
        bin.install "goreleaser-testing"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.33.0/goreleaser-testing_0.33.0_Linux_x86_64.tar.gz"
      sha256 "135492641604d3d4d566054511d352683807d8f9da2127002e2dbbb58483737b"

      def install
        bin.install "goreleaser-testing"
      end
    end
  end
end
