# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jeeves < Formula
  desc "A TUI for AI agent sessions."
  homepage "https://github.com/robinovitch61/jeeves"
  version "0.3.0"

  on_macos do
    url "https://github.com/robinovitch61/jeeves/releases/download/v0.3.0/jeeves_0.3.0_Darwin_all.tar.gz"
    sha256 "c7226900dcaf950573aa8ccbfed852b3d55122787a26eee0ceebb0e1ebe21021"

    define_method(:install) do
      bin.install "jeeves"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/jeeves/releases/download/v0.3.0/jeeves_0.3.0_Linux_x86_64.tar.gz"
      sha256 "877617b73f49f3304a5514f116cca0bec8613b9633ec3b8810e83242e82c1a8e"
      define_method(:install) do
        bin.install "jeeves"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/jeeves/releases/download/v0.3.0/jeeves_0.3.0_Linux_arm64.tar.gz"
      sha256 "18e796bb986babe9be8989e2e209a7d13cb301be3755dd1e4d765c3a8978eda0"
      define_method(:install) do
        bin.install "jeeves"
      end
    end
  end
end
