# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jeeves < Formula
  desc "A TUI for AI agent sessions."
  homepage "https://github.com/robinovitch61/jeeves"
  version "0.2.0"

  on_macos do
    url "https://github.com/robinovitch61/jeeves/releases/download/v0.2.0/jeeves_0.2.0_Darwin_all.tar.gz"
    sha256 "adad16675bcea37620d89b850f150681073c62a6cd544767f895f2efc89a140f"

    define_method(:install) do
      bin.install "jeeves"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/jeeves/releases/download/v0.2.0/jeeves_0.2.0_Linux_x86_64.tar.gz"
      sha256 "739d9feaa1783e60316dcd52e533e8fc52dc0d79748f922c647ca18d423e60de"
      define_method(:install) do
        bin.install "jeeves"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/jeeves/releases/download/v0.2.0/jeeves_0.2.0_Linux_arm64.tar.gz"
      sha256 "eefa5db4883dd3168b1c60591b3b5167342a2251ed591afd0ee5465a36246c69"
      define_method(:install) do
        bin.install "jeeves"
      end
    end
  end
end
