# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc "An interactive Kubernetes log viewer for your terminal."
  homepage "https://github.com/robinovitch61/kl"
  version "0.9.1"

  on_macos do
    url "https://github.com/robinovitch61/kl/releases/download/v0.9.1/kl_0.9.1_Darwin_all.tar.gz"
    sha256 "8bd94c47f83d15c402a29094e38936f37da79df125a2a1dd1b7e9849d73a5ae0"

    define_method(:install) do
      bin.install "kl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/kl/releases/download/v0.9.1/kl_0.9.1_Linux_x86_64.tar.gz"
      sha256 "2fb308cbc9dc0fd85a5fb4233e209d986fd55f7a7d774713c7583dbfc83ae2e9"
      define_method(:install) do
        bin.install "kl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/kl/releases/download/v0.9.1/kl_0.9.1_Linux_arm64.tar.gz"
      sha256 "ec86fe5d2cbf6c9960afb50251016ecc4e6257ff0d96313341e3f972897c9be6"
      define_method(:install) do
        bin.install "kl"
      end
    end
  end
end
