# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc "An interactive Kubernetes log viewer for your terminal."
  homepage "https://github.com/robinovitch61/kl"
  version "0.9.0"

  on_macos do
    url "https://github.com/robinovitch61/kl/releases/download/v0.9.0/kl_0.9.0_Darwin_all.tar.gz"
    sha256 "1d7c0525a11043a9faa1d82ce5c21914c0187c4fb7dae2944a01e81db315cf6c"

    define_method(:install) do
      bin.install "kl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/kl/releases/download/v0.9.0/kl_0.9.0_Linux_x86_64.tar.gz"
      sha256 "6e6a9cb8363e1a43a32c409891742907b1eb66d7d72b766c5db7c38d5804c434"
      define_method(:install) do
        bin.install "kl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/kl/releases/download/v0.9.0/kl_0.9.0_Linux_arm64.tar.gz"
      sha256 "560b085beb324e49e274f6e17661b8bc07e7978c2c417739317317b33e0fa246"
      define_method(:install) do
        bin.install "kl"
      end
    end
  end
end
