# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A terminal pager with search, filter, and selection."
  homepage "https://github.com/robinovitch61/lore"
  version "0.3.1"

  on_macos do
    url "https://github.com/robinovitch61/lore/releases/download/v0.3.1/lore_0.3.1_Darwin_all.tar.gz"
    sha256 "764cc0400214da65b7686758e29966bdbbb916c212419546000e63571e707dd4"

    define_method(:install) do
      bin.install "lore"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.3.1/lore_0.3.1_Linux_x86_64.tar.gz"
      sha256 "4c4ec50a9ae5e99826808adcbc78dde2926d265c4bb13da79ed5f4c6807b3a84"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.3.1/lore_0.3.1_Linux_arm64.tar.gz"
      sha256 "08d2b29d57bddd961ad52bf4bcf113919a9b10613191b80034e23acc0281c04e"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end
end
