# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A terminal pager with search, filter, and selection."
  homepage "https://github.com/robinovitch61/lore"
  version "0.1.1"

  on_macos do
    url "https://github.com/robinovitch61/lore/releases/download/v0.1.1/lore_0.1.1_Darwin_all.tar.gz"
    sha256 "0960e1341238a11269b31eaf4c32a54765442e12262ec3ff4d692ab15fbe95ae"

    define_method(:install) do
      bin.install "lore"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.1.1/lore_0.1.1_Linux_x86_64.tar.gz"
      sha256 "d2c2dd4b916bc634aa5530b80fdd0a76822cfe78fc48a6e56dfd3ed848f9a43f"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.1.1/lore_0.1.1_Linux_arm64.tar.gz"
      sha256 "25cffb8da1a8aafc55138a425e7c681cadcabe08a976a1bd10e2b7e1de0df9b0"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end
end
