# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A terminal pager with search, filter, and selection."
  homepage "https://github.com/robinovitch61/lore"
  version "0.4.0"

  on_macos do
    url "https://github.com/robinovitch61/lore/releases/download/v0.4.0/lore_0.4.0_Darwin_all.tar.gz"
    sha256 "a41f9bc9ef78306e823ffe3e7bf3ad074857aab4434ac2b405d481716bdf4e69"

    define_method(:install) do
      bin.install "lore"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.4.0/lore_0.4.0_Linux_x86_64.tar.gz"
      sha256 "50467f9b363b28ad807f82f578d3e9d9612d6b43455ddfdfa0e61377510ee9c1"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/lore/releases/download/v0.4.0/lore_0.4.0_Linux_arm64.tar.gz"
      sha256 "82034a313edf243830a3a93305587eefa0e89fdba1891bb3973810ec0152e62c"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end
end
