# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebtoonDl < Formula
  desc "Download webtoon comics as pdfs."
  homepage "https://github.com/robinovitch61/webtoon-dl"
  version "0.0.2"

  on_macos do
    url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.2/webtoon-dl_0.0.2_Darwin_all.tar.gz"
    sha256 "a3be3dc05a4fd5c239a34065d22d01ca1f0d89818ea32d73da2a9b9056da2a13"

    def install
      bin.install "webtoon-dl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.2/webtoon-dl_0.0.2_Linux_arm64.tar.gz"
      sha256 "791967f84e75bd248fbfc3f811c2f4b6845db69436cf424405a8abf7a878b7f9"

      def install
        bin.install "webtoon-dl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.2/webtoon-dl_0.0.2_Linux_x86_64.tar.gz"
      sha256 "57658f04e5a092079cf68bf94efe68d45ee9b170fb54133acf0350fa0c62e943"

      def install
        bin.install "webtoon-dl"
      end
    end
  end
end
