# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebtoonDl < Formula
  desc "Download webtoon comics as pdfs."
  homepage "https://github.com/robinovitch61/webtoon-dl"
  version "0.0.5"

  on_macos do
    url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.5/webtoon-dl_0.0.5_Darwin_all.tar.gz"
    sha256 "22f94cb0b2c4ff6d7bc458b97ea83993e8ff964ea6fadf9e22729be922df21d6"

    def install
      bin.install "webtoon-dl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.5/webtoon-dl_0.0.5_Linux_x86_64.tar.gz"
      sha256 "f8a79b5f6b67fede5beb79cb08f319f8e4e5b9a0efbfef1249f39130edb6ac69"

      def install
        bin.install "webtoon-dl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinovitch61/webtoon-dl/releases/download/v0.0.5/webtoon-dl_0.0.5_Linux_arm64.tar.gz"
      sha256 "d125178aa15b00893fa135c79b626aad03052d0c1e8f97611a09a56e887817e6"

      def install
        bin.install "webtoon-dl"
      end
    end
  end
end
